### ISSUE TITLE
Conflicting values for soil_horizon

### ISSUE THREAD

**Issue by turbomam** [microbiomedata/mixs-6-2-release-candidate#181]
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:Columns only found in the MIxS sheet: ['Section']
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:Columns only found in the environmental_packages sheet: []
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:duplication_comment: Classes agriculture has/have duplicate values in Requirement for soil_horizon: C
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:dupe_frame:             class Requirement Structured comment name
1576  agriculture           C            soil_horizon
1699  agriculture           C            soil_horizon
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:duplication_comment: Classes agriculture has/have duplicate values in MIXS ID for soil_horizon: MIXS:0001291, MIXS:0001082
INFO:mixs_envo_struct_knowl_extraction.mixs_linkml_from_xlsx:dupe_frame:             class       MIXS ID Structured comment name
1576  agriculture  MIXS:0001291            soil_horizon
1699  agriculture  MIXS:0001082            soil_horizon

**Comment by only1chunts** [comment]
The ticket [#529](https://github.com/GenomicsStandardsConsortium/mixs/issues/529) in MIxS repo states that MIXS:0001291 is wrong and should be corrected to be MIXS:0001082.
And that the Structured Comment name of MIXS:0001082 should be "soil_horizon" [#232](https://github.com/GenomicsStandardsConsortium/mixs/issues/232)
So they are confirmed changes that you can make in this version, if its possible to reference the tickets 232 & 529 in some way then that would be great, but if not its not a big deal.

**Comment by turbomam** [comment]
> The ticket [#529](https://github.com/GenomicsStandardsConsortium/mixs/issues/529) in MIxS repo states that MIXS:0001291 is wrong

I really appreciate by your quick and evidenced responses to these issue!

**Comment by turbomam** [comment]
What does 
> is wrong and should be corrected
mean?

In the MIxS excel file, agriculture uses both the MIXS:0001291 and the MIXS:0001082 term. So I think the correction you're mentioning would technically create a duplicate agriculture MIXS:0001082 pairing.

Would it be OK to just totally delete MIXS:0001291?

**Comment by only1chunts** [comment]
yes, remove the duplicate so Ag package only has 1 instance of MIXS:0001082
